### ISSUE TITLE
Jupyter Notebook is not starting

### ISSUE THREAD

**Issue by vinayakbhadage** [rapidsai/helm-chart#1]
Hi ,
I was using this chart on AKS .. It was working perfectly fine even after updating the dask dependency  to 4.1.6 but since your last release container is not staring with jupyter notebook. 

Thanks and Regards,
-Vinayak

**Comment by jacobtomlinson** [comment]
Apologies for the delay here. Are you still experiencing this?

**Comment by vinayakbhadage** [comment]
Now using Jupyter notebook from dask scheduler. Dont need separate pod for notebook.

Thanks,
-Vinayak

**Comment by JulianWgs** [comment]
I think I've the same issue. I'm getting a CrashLoopBackOff with this log:

$ kubectl logs rapidsai-jupyter-5584bbf8b4-8p9k6
bash: /rapids/notebooks/utils/start-jupyter.sh: No such file or directory

**Comment by JulianWgs** [comment]
I was using the standard helm chart without further configuration (despite number of worker replicas) on Amazon EKS.
