### ISSUE TITLE
Misconfigurations and Failures

### ISSUE THREAD

**Issue by quasiben** [rapidsai/helm-chart#10]
Workers pod fails to come up.  From `kubectl logs`:

```
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.20.0.11:42771'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/envs/rapids/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/distributed/process.py", line 191, in _run
    target(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/distributed/worker.py", line 489, in __init__
    os.makedirs(local_directory)
  File "/opt/conda/envs/rapids/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

I believe this issue has been fixed in latest dask/distributed ? 

There is also an outdated scheduler setup:

```
/opt/conda/envs/rapids/lib/python3.6/site-packages/distributed/cli/dask_scheduler.py:148: UserWarning: The --bokeh-port flag has been renamed to --dashboard-address. Consider adding ``--dashboard-address :8787``
  "Consider adding ``--dashboard-address :%d`` " % bokeh_port
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:      tcp://10.20.1.8:8786
distributed.scheduler - INFO -   dashboard at:                     :8787
distributed.utils - ERROR - addresses should be strings or tuples, got None
Traceback (most recent call last):

```

**Comment by jacobtomlinson** [comment]
I think this needs to be fixed upstream in the Dask chart

**Comment by ghost** [comment]
I also encountered this issue.

**Comment by jacobtomlinson** [comment]
This is a known bug in Dask which has been fixed. Using the 0.15 nighlies works as expected.

**Comment by daddydrac** [comment]
Is this fixed?

**Comment by daddydrac** [comment]
When I run:
```helm install --name name --namespace mynamespace rapidsai```

I get:
```Error: unknown flag: --name```

**Comment by jacobtomlinson** [comment]
@joehoeller that looks like you are using Helm 2 syntax with Helm 3. 

You need to do `helm install name --namespace namespace rapidsai/rapidsai`

**Comment by daddydrac** [comment]
Thanks. I’ll test it out and let you know.

**Comment by xjantoth** [comment]
Hi, where are the template files? Thx

**Comment by daddydrac** [comment]
Per Jan’s statement, this would explain why it doesn’t work.

**Comment by daddydrac** [comment]
@jacobtomlinson  any updates?

**Comment by jacobtomlinson** [comment]
@joehoeller the action is on you to test the command I provided above.

@xjantoth the template files mostly live in the [dask helm chart](https://github.com/dask/helm-chart), which is a [dependency](https://github.com/rapidsai/helm-chart/blob/main/rapidsai/requirements.yaml) of this one.

**Comment by daddydrac** [comment]
@jacobtomlinson working on it, as i am using chart museum and some other things... just to clarify, this is the whole RAPIDS suite + Dask for K8s, correct? (Not just cuML?)

**Comment by jacobtomlinson** [comment]
@joehoeller yes this is all of RAPIDS

**Comment by daddydrac** [comment]
@jacobtomlinson plz see -> https://github.com/dask/dask-kubernetes/issues/267

Can we use dask version 4.5 or need to stick w/ 4.2?

**Comment by quasiben** [comment]
I think you should be good with the latest helm chart, `4.5` ?  Is this giving you any issues ?

**Comment by daddydrac** [comment]
It doesn’t deploy. It breaks. 
I’m going to have to figure out how to make my own helm chart for this. I’ve had several Ops ppl look at it and they say the same.

**Comment by quasiben** [comment]
Can you post the command you ran and the error you received ?

**Comment by daddydrac** [comment]
I’m using rancher & chart museum. I think I need to create a questions.yaml
file. I just don’t know what the variables are.

**Comment by jacobtomlinson** [comment]
@joehoeller any further details about the errors you are seeing would be much appreciated.

I've just merged a few changes to use the latest Dask dependency and RAPIDS images and tested again locally and am able to deploy using helm following [these instructions](https://github.com/rapidsai/helm-chart#from-source).

I've also had a look at the Rancher docs and it looks like `questions.yaml` is an optional file that Rancher optimised charts can add for an improved GUI experience. If you are interested in creating one and contributing it then that would be great! You can find a table of variables in the [README](https://github.com/rapidsai/helm-chart#configuration).

**Comment by daddydrac** [comment]
I’ll get the questions.yaml over to you, is there a doc that shows the
variables?

I can get errors later after all my meetings this am :/

**Comment by jacobtomlinson** [comment]
Great!

> is there a doc that shows the variables?

Yeah all variables are listed in the project README.

**Comment by daddydrac** [comment]
Thank you

**Comment by daddydrac** [comment]
@jacobtomlinson @quasiben 
So I have the questions.yaml file done. But the prob is auto scheduling GPUs w dask. Let’s say in the code I tell dask to give me 5 more pods. How can I schedule GPUs for those pods automatically?

**Comment by quasiben** [comment]
I assume in this case you will be using dask-kubernetes (this will allow you to programmatically scheduler more workers).  In this case, you will have already defined a worker spec like the following which contains a directive for scheduling pods with GPUs:


```
# worker-spec.yml

kind: Pod
metadata:
  labels:
    foo: bar
spec:
  restartPolicy: Never
  containers:
  - image: rapidsai/rapidsai:latest
    imagePullPolicy: IfNotPresent
    args: [dask-cuda-worker]
    name: dask
    resources:
      limits:
        cpu: "2"
        memory: 6G
      requests:
        cpu: "2"
        memory: 6G
      limits:
          nvidia.com/gpu: 1
```

And then you can use the spec like the following.  
```python
from dask_kubernetes import KubeCluster

cluster = KubeCluster.from_yaml('worker-spec.yml')
cluster.scale(10)  # specify number of workers explicitly

cluster.adapt(minimum=1, maximum=100)  # or dynamically scale based on current workload
```

I can push some more docs for GPU specifics but this is generally laid out here https://kubernetes.dask.org/en/latest/kubecluster.html

**Comment by daddydrac** [comment]
@xjantoth did we ever add this workerspec? (see above)

**Comment by xjantoth** [comment]
thanks guys for posting this worker-specs.yaml I will definitelly start cluster and try it.

ao once I will add let's say 4  xtra workers using your proposal, can you please provide some simple code to run on the top of these  gpu workers just to see that code is running across of these extra workers in distributed fashion? thanks so much -jan

**Comment by daddydrac** [comment]
issue still persists

**Comment by jacobtomlinson** [comment]
@joehoeller are you referring to the `FileNotFoundError: [Errno 2] No such file or directory: ''` issue?

**Comment by jacobtomlinson** [comment]
Closing as this project is now deprecated
