### ISSUE TITLE
Helm Chart not working on Kubernetes

### ISSUE THREAD

**Issue by ghost** [rapidsai/helm-chart#3]
I was to ask microk8s community to understand why the RAPIDS AI helm-chart won't work on the kubernetes cluster with GPUs enabled and they concluded that there is something wrong with the chart. 
They've tried it on a `k8 bare metal` and it results in failures.
Can you look into why the Dask-Cuda-Workers aren't working?

**Comment by jacobtomlinson** [comment]
Can you please provide a reproducible example of this not working?

**Comment by ghost** [comment]
The team at microk8s used a baremetal k8s and received the following errors: 
Reference [Microk8s GITHUB#1370](https://github.com/ubuntu/microk8s/issues/1370)
```
NAMESPACE                         NAME                                                          READY   STATUS         RESTARTS   AGE
ingress-nginx-kubernetes-worker   pod/default-http-backend-kubernetes-worker-7f969db96f-4lc95   1/1     Running        0          4h30m
ingress-nginx-kubernetes-worker   pod/nginx-ingress-controller-kubernetes-worker-k4v88          1/1     Running        0          4h30m
kube-system                       pod/coredns-6b59b8bd9f-zx7wp                                  1/1     Running        0          4h30m
kube-system                       pod/kube-state-metrics-69f474f8cb-4m7qs                       1/1     Running        0          4h30m
kube-system                       pod/metrics-server-v0.3.6-74c87686d-q99qq                     2/2     Running        0          4h30m
kube-system                       pod/nvidia-device-plugin-daemonset-4hwcp                      1/1     Running        0          4h29m
kube-system                       pod/tiller-deploy-fc55974f-67qz6                              1/1     Running        0          3m51s
kubernetes-dashboard              pod/dashboard-metrics-scraper-78d587b6b-sw994                 1/1     Running        0          4h30m
kubernetes-dashboard              pod/kubernetes-dashboard-7b76878768-dh9kt                     1/1     Running        0          4h30m
mynamespace                       pod/rapidsai-jupyter-76fc4b96bb-dg7tm                         0/1     Pending        0          60s
mynamespace                       pod/rapidsai-scheduler-7675655dc6-9qxtq                       0/1     ErrImagePull   0          60s
mynamespace                       pod/rapidsai-worker-77c9d9d8cb-6jmlt                          0/1     Evicted        0          60s
mynamespace                       pod/rapidsai-worker-77c9d9d8cb-fjks2                          0/1     Pending        0          60s
mynamespace                       pod/rapidsai-worker-77c9d9d8cb-lngll                          0/1     Pending        0          60s
mynamespace                       pod/rapidsai-worker-77c9d9d8cb-x4ggc                          0/1     Pending       
```
Example Scenario: the microk8s team tried on k8 baremetas cluster, but I can give you example on microk8s which provides same results.

3 machines in `kubernetes cluster`: 
- `iMAC Ubuntu 20.04 with no Nvidia GPU` (Kubernetes Master)
- `Razer Ubuntu 20.04 with Nvidia GPU RTX 2080 TI`
- `Alienware Ubuntu 20.04 with Nvidia GPU RTX 2080 TI`

Install `NVIDIA` prerequisites on Razer and Alienware: 

- `Install Docker`
- `Install Nvidia Container Toolkit ` [GITHUB - Nvidia Docker](https://github.com/NVIDIA/nvidia-docker)

Install microk8s on all machines: 
- `sudo snap install microk8s --classic`

On the iMAC master node: enable dns, dashboard, ingress, metallb, helm, and helm3. 
- `microk8s enable dns dashboard ingress metallb helm helm3`

Join nodes in cluster: 
On the IMAC master node:
- `microk8s add-node` 
- `record token from previous step`

On the Razer and Alienware: 
- `microk8s join <token>`

Install the NVIDIA helm chart using helm 3
- `microk8s helm3 repo add nvdp https://nvidia.github.io/k8s-device-plugin`
- `microk8s helm3 repo update`
- `microk8s helm3 install \`
    `--version=0.6.0 \`
    `--generate-name \`
    `nvdp/nvidia-device-plugin`

Install the RAPIDS AI HELM chart: 
- `git clone https://github.com/rapidsai/helm-chart helm-chart`
- `cd helm-chart`
- `helm dep update rapidsai`
- `helm install --name rapidsai --namespace rapids rapidsai`

Kubernetes Dashboard: 
- `microk8s kubectl proxy`
- Browser: `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#/login`
Note: You can modify the script to skip credentials. 

If you look at the --namespace rapids ai, you'll see that the `dask workers` are pending. 

Please help. Because we can't get the helm chart to work, we are currently using ssh which is not an ideal approach when we plan to scale to more machines. 

Thanks, 

Vinh

**Comment by jacobtomlinson** [comment]
Could you please run `kubectl describe <pod name>` for the pending pods. Especially the one with the `ErrImagePull` error.

**Comment by ghost** [comment]
Sorry for the delay, I decided to invest in some machines to create a true Kubeneretes environment on baremetal. I'm currently using `Ubuntu 20.04` with `kubernetes packages`.
Before I installed the `rapids ai helm chart`, I installed the `nvidia container toolkit` via `docker` on all machines with NVIDIA GPUSs. I also performed a test on each machine as follows: `docker run --gpus all --it nvidia/cuda:10.0 nvidia-smi which returned expected results. 
After the `nvidia container toolkit`, I installed the `Nvidia K8 Helm Chart`: 
```
helm repo add nvdp https://nvidia.github.io/k8s-device-plugin
 
helm repo update
 
helm install \
    --version=0.6.0 \
    --generate-name \
    nvdp/nvidia-device-plugin
````
After all the pods are running, I installed the rapids ai `helm chart`
```
git clone https://github.com/rapidsai/helm-chart helm-chart
cd helm-chart
helm dep update rapidsai
helm install –-generate-name --namespace rapidsai rapidsai
```
As expected, it the `worker pods` doesn't run because 'kube describe <pod>` gets the following errors:
```
Name:           rapidsai-worker-8c5885f88-2crsg
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=rapidsai
                component=worker
                pod-template-hash=8c5885f88
                release=rapidsai
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/rapidsai-worker-8c5885f88
Containers:
  rapidsai-worker:
    Image:      rapidsai/rapidsai:cuda10.0-runtime-ubuntu16.04
    Port:       8789/TCP
    Host Port:  0/TCP
    Args:
      dask-cuda-worker
      rapidsai-scheduler:8786
      --nthreads
      1
      --memory-limit
      3G
      --no-dashboard
    Limits:
      cpu:             1
      memory:          3G
      nvidia.com/gpu:  1
    Requests:
      cpu:             1
      memory:          3G
      nvidia.com/gpu:  1
    Environment:       <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-l8pz2 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  default-token-l8pz2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-l8pz2
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 nvidia.com/gpu=present:NoSchedule
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  33m (x39 over 88m)   default-scheduler  0/3 nodes are available: 3 Insufficient nvidia.com/gpu.
  Warning  FailedScheduling  84s (x5 over 7m24s)  default-scheduler  0/3 nodes are available: 3 Insufficient nvidia.com/gpu.
```
I'm trying to understand what I'm missing in my setup because the helm chart always states Insufficient nvidia.com/gpu. 
Do you have any suggestions on setting up the NVIDIA environment?

**Comment by jacobtomlinson** [comment]
I'm afraid cluster setup is out of scope for this project. 

Some things I can think of are:

- Have you installed the [device plugin](https://github.com/NVIDIA/k8s-device-plugin)?
- Have you set the NVIDIA runtime to be the default.
- Only one pod can use a GPU at a time. Are there other pods running using your GPUs?
- Are you able to schedule other GPU jobs like [this one](https://github.com/NVIDIA/k8s-device-plugin#running-gpu-jobs)?

Other than that I suggest you check the [NVIDIA documentation](https://docs.nvidia.com/datacenter/kubernetes/kubernetes-upstream/index.html) and perhaps reach out to other support communities.
