### ISSUE TITLE
How many GPUs are necessary?

### ISSUE THREAD

**Issue by JulianWgs** [rapidsai/helm-chart#8]
Do I need a GPU for each worker, the scheduler and the notebook?

For example if I want a cluster with 4 GPU workers will I need 6 GPUs?

Thanks in advance!

**Comment by jacobtomlinson** [comment]
You need one per worker and one for the notebook. The scheduler doesn't require one. So for 4 workers and 1 notebook you will need 5 GPUs.

**Comment by JulianWgs** [comment]
Thank you for the quick answer!
